import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { getRoutes } from './../lib/routes';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Motive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ul>
          <li>
            <Link href={getRoutes('root')}>
              <a>Home</a>
            </Link>
          </li>
          <li>
          <Link href={getRoutes('today')}>
              <a>today's tasks</a>
            </Link>
          </li>
          <li>
          <Link href={getRoutes('settings')}>
              <a>settings</a>
            </Link>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default Home;
