import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { getRoutes } from "./../lib/routes";
import BaseLayout from "@/components/templates/Layouts/BaseLayout";

const Home: NextPage = () => {
  const links = [
    { title: "Home", path: "root" },
    { title: "today's tasks", path: "today" },
    { title: "settings", path: "settings" },
  ];

  return (
    <BaseLayout>
      <Head>
        <title>Motive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ul>
          {links.map((link, idx) => (
            <li key={idx}>
              <Link href={getRoutes(link.path)}>
                <a>{link.title}</a>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </BaseLayout>
  );
};

export default Home;
